nohup: ignoring input
Args in experiment:
[1mBasic Config[0m
  Task Name:          classification      Is Training:        1                   
  Model ID:           UserIdentify1       Model:              TimesNet            

[1mData Loader[0m
  Data:               UEA                 Root Path:          ./dataset/360_video_viewing_dataset/transfer_10_10
  Data Path:          ETTh1.csv           Features:           M                   
  Target:             OT                  Freq:               h                   
  Checkpoints:        ./checkpoints/      

[1mModel Parameters[0m
  Top k:              2                   Num Kernels:        6                   
  Enc In:             7                   Dec In:             7                   
  C Out:              7                   d model:            32                  
  n heads:            8                   e layers:           2                   
  d layers:           1                   d FF:               32                  
  Moving Avg:         25                  Factor:             1                   
  Distil:             1                   Dropout:            0.1                 
  Embed:              timeF               Activation:         gelu                
  Output Attention:   0                   

[1mRun Parameters[0m
  Num Workers:        10                  Itr:                1                   
  Train Epochs:       30                  Batch Size:         16                  
  Patience:           10                  Learning Rate:      0.001               
  Des:                Exp                 Loss:               MSE                 
  Lradj:              type1               Use Amp:            0                   

[1mGPU[0m
  Use GPU:            0                   GPU:                0                   
  Use Multi GPU:      0                   Devices:            0,1,2,3             

[1mDe-stationary Projector Params[0m
  P Hidden Dims:      128, 128            P Hidden Layers:    2                   

Use CPU
47484
5273
>>>>>>>start training : classification_UserIdentify1_TimesNet_UEA_ftM_sl10_ll48_pl0_dm32_nh8_el2_dl1_df32_fc1_ebtimeF_dtTrue_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
47484
5273
5273
	iters: 100, epoch: 1 | loss: 2.2577157
	speed: 0.1654s/iter; left time: 14709.7247s
	iters: 200, epoch: 1 | loss: 1.8901129
	speed: 0.1436s/iter; left time: 12758.6937s
	iters: 300, epoch: 1 | loss: 1.3629661
	speed: 0.1480s/iter; left time: 13132.9507s
	iters: 400, epoch: 1 | loss: 1.3753209
	speed: 0.1583s/iter; left time: 14033.1049s
	iters: 500, epoch: 1 | loss: 1.0703156
	speed: 0.1358s/iter; left time: 12021.2296s
	iters: 600, epoch: 1 | loss: 1.4626158
	speed: 0.1398s/iter; left time: 12368.2768s
	iters: 700, epoch: 1 | loss: 1.0741160
	speed: 0.1704s/iter; left time: 15050.7816s
	iters: 800, epoch: 1 | loss: 1.2129024
	speed: 0.1351s/iter; left time: 11924.0568s
	iters: 900, epoch: 1 | loss: 1.5407989
	speed: 0.1608s/iter; left time: 14173.0255s
	iters: 1000, epoch: 1 | loss: 0.8087158
	speed: 0.1422s/iter; left time: 12522.0490s
	iters: 1100, epoch: 1 | loss: 0.8829635
	speed: 0.1636s/iter; left time: 14386.3860s
Traceback (most recent call last):
  File "/users/PMIU0211/kelyu/GitHub/thuml/Time-Series-Library/run.py", line 149, in <module>
    exp.train(setting)
  File "/users/PMIU0211/kelyu/GitHub/thuml/Time-Series-Library/exp/exp_classification.py", line 102, in train
    for i, (batch_x, label, padding_mask) in enumerate(train_loader):
  File "/users/PMIU0211/kelyu/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/users/PMIU0211/kelyu/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/users/PMIU0211/kelyu/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/users/PMIU0211/kelyu/.local/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/users/PMIU0211/kelyu/.local/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/users/PMIU0211/kelyu/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/users/PMIU0211/kelyu/GitHub/thuml/Time-Series-Library/data_provider/data_factory.py", line 68, in <lambda>
    collate_fn=lambda x: collate_fn(x, max_len=args.seq_len)
  File "/users/PMIU0211/kelyu/GitHub/thuml/Time-Series-Library/data_provider/uea.py", line 35, in collate_fn
    X[i, :end, :] = features[i][:end, :]
IndexError: too many indices for tensor of dimension 1

